services:
  ros2-webots:
    build: .
    container_name: jazzy_webots_sim
    stop_grace_period: 0s
    privileged: true
    network_mode: host
    ipc: host
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - XDG_RUNTIME_DIR=/tmp
      - WEBOTS_OFFSCREEN_NO_GUI=0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - .:/root/hexadrone_ws:rw
      - /root/hexadrone_ws/build
      - /root/hexadrone_ws/install
      - ./.container_fish_history:/root/.local/share/fish/fish_history:rw
    devices:
      - /dev/input/js0:/dev/input/js0:rw  # Change js0 (Joystick device) if differs on your machine, in launch.py as well
    group_add:
      - keep-groups
    device_requests:
      - driver: nvidia
        count: all
        capabilities: [gpu]
