; PlatformIO Project Configuration File for Hexadrone ESP32

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

; --- Serial Monitor ---
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; --- Build Options ---
board_build.filesystem = littlefs
build_unflags = 
    -std=gnu++11
build_flags =
    -I include
    -std=gnu++17

; --- Dependencies ---
lib_ldf_mode = deep+
lib_ignore = WebServer
lib_deps =
    symlink://../hexadrone_core
    AlfredoSystems/AlfredoCRSF @ 1.0.1
    RobTillaart/INA228 @ 0.4.1
    adafruit/Adafruit PWM Servo Driver Library @ 3.0.1
    mathieucarbou/ESPAsyncWebServer @ 3.3.2
    
    ; Built-in libraries
    Wire
    LittleFS

; --- Wireless OTA Upload ---
upload_protocol = espota
upload_port = hexadrone.local
